(*
 *	This file was automaticly generated by OBumpRev 0.2.5.
 *	DO NOT EDIT THIS FILE!
 *)

<* STANDARD- *> <* INITIALISE- *> <* MAIN- *>

MODULE	ConvertSwitchesRev;

IMPORT	SYSTEM;

CONST	version	*= 1;
	revision*= 6;
	date	*= "17.4.95";
	vers	*= "ConvertSwitches 1.6";
	vString	*= "ConvertSwitches 1.6 (17.4.95)\r\n";
	versTag	*= "$VER: ConvertSwitches 1.6 (17.4.95)\r\n";

BEGIN	(* Make sure that version string is visible *)
	SYSTEM.PUTREG (0, SYSTEM.ADR (versTag))
END	ConvertSwitchesRev.
