(*
 *	This file was automaticly generated by OBumpRev 0.2.5.
 *	DO NOT EDIT THIS FILE!
 *)

<* STANDARD- *> <* INITIALISE- *> <* MAIN- *>

MODULE	OCRev;

IMPORT	SYSTEM;

CONST	version	*= 5;
	revision*= 34;
	date	*= "2.7.95";
	vers	*= "OC 5.34";
	vString	*= "OC 5.34 (2.7.95)\r\n";
	versTag	*= "$VER: OC 5.34 (2.7.95)\r\n";

BEGIN	(* Make sure that version string is visible *)
	SYSTEM.PUTREG (0, SYSTEM.ADR (versTag))
END	OCRev.
