(*
 *	This file was automaticly generated by OBumpRev 0.2.5.
 *	DO NOT EDIT THIS FILE!
 *)

<* STANDARD- *> <* INITIALISE- *> <* MAIN- *>

MODULE	ODRev;

IMPORT	SYSTEM;

CONST	version	*= 1;
	revision*= 12;
	date	*= "15.6.95";
	vers	*= "OD 1.12";
	vString	*= "OD 1.12 (15.6.95)\r\n";
	versTag	*= "$VER: OD 1.12 (15.6.95)\r\n";

BEGIN	(* Make sure that version string is visible *)
	SYSTEM.PUTREG (0, SYSTEM.ADR (versTag))
END	ODRev.
