(*
 *      This file was automaticly generated by OBumpRev 0.2.4.
 *      DO NOT EDIT THIS FILE!
 *)

<* STANDARD- *> <* INITIALISE- *> <* MAIN- *>

MODULE  OELRev;

IMPORT  SYSTEM;

CONST   version *= 0;
        revision*= 5;
        date    *= "15.6.95";
        vers    *= "OEL 0.5.8";
        vString *= "OEL 0.5.8 (15.6.95)\r\n";
        versTag *= "$VER: OEL 0.5.8 (15.6.95)\r\n";

BEGIN   (* Make sure that version string is visible *)
        SYSTEM.PUTREG (0, SYSTEM.ADR (versTag))
END     OELRev.
